#!/usr/bin/env bash
# One-time Google Cloud setup: project APIs, private bucket, first data push, Cloud Run deploy.
# Prerequisites: gcloud CLI installed, `gcloud auth login`, billing enabled on project.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=scripts/lib/cloud-env.sh
source "${ROOT}/scripts/lib/cloud-env.sh"
load_cloud_env

REGION="${GOLF_CLOUD_RUN_REGION:-us-central1}"
SERVICE="${GOLF_CLOUD_RUN_SERVICE:-golf-dashboard}"

die() {
  echo "$*" >&2
  exit 1
}

if ! command -v gcloud >/dev/null 2>&1; then
  die "Install Google Cloud SDK: https://cloud.google.com/sdk/docs/install"
fi

if ! gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | grep -q .; then
  die "Run: gcloud auth login"
fi

PROJECT="$(gcloud config get-value project 2>/dev/null || true)"
if [[ -z "$PROJECT" || "$PROJECT" == "(unset)" ]]; then
  echo "No default project. Pick one:"
  gcloud projects list --format='table(projectId,name)'
  read -r -p "Project ID: " PROJECT
  gcloud config set project "$PROJECT"
fi

echo "Using project: ${PROJECT}"

echo "Enabling APIs..."
if ! gcloud services enable \
  run.googleapis.com \
  storage.googleapis.com \
  artifactregistry.googleapis.com \
  cloudbuild.googleapis.com \
  --project="$PROJECT" \
  --quiet 2>&1; then
  echo "" >&2
  die "$(cat <<EOF
Cannot enable APIs on project '${PROJECT}'.

Your account needs Owner or Editor on the project (or Service Usage Admin to enable APIs).

Fix options:
  1. Use a project you own:
       gcloud projects list
       gcloud config set project YOUR_PROJECT_ID
       ./scripts/setup-cloud-mobile.sh

  2. Create a new personal project:
       gcloud projects create golf-dashboard-\$(date +%Y%m) --name='Golf Dashboard'
       gcloud billing accounts list
       gcloud billing projects link golf-dashboard-\$(date +%Y%m) --billing-account=BILLING_ACCOUNT_ID
       gcloud config set project golf-dashboard-\$(date +%Y%m)
       ./scripts/setup-cloud-mobile.sh

  3. If '${PROJECT}' is shared/team-owned, ask the project owner to grant you roles/owner or roles/editor.
EOF
)"
fi

if [[ -z "${GOLF_DATA_BUCKET:-}" ]]; then
  SUFFIX="$(echo "$PROJECT" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9-' '-' | cut -c1-20)"
  DEFAULT_BUCKET="${SUFFIX}-golf-data"
  read -r -p "GCS bucket name [${DEFAULT_BUCKET}]: " GOLF_DATA_BUCKET
  GOLF_DATA_BUCKET="${GOLF_DATA_BUCKET:-$DEFAULT_BUCKET}"
fi

if ! gcloud storage buckets describe "gs://${GOLF_DATA_BUCKET}" --project="$PROJECT" >/dev/null 2>&1; then
  echo "Creating bucket gs://${GOLF_DATA_BUCKET} in ${REGION}..."
  gcloud storage buckets create "gs://${GOLF_DATA_BUCKET}" \
    --location="$REGION" \
    --project="$PROJECT" \
    --uniform-bucket-level-access
else
  echo "Bucket gs://${GOLF_DATA_BUCKET} already exists."
fi

if [[ -z "${GOLF_ACCESS_TOKEN:-}" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    GOLF_ACCESS_TOKEN="$(openssl rand -hex 24)"
  else
    GOLF_ACCESS_TOKEN="$(python3 -c 'import secrets; print(secrets.token_hex(24))')"
  fi
  echo "Generated GOLF_ACCESS_TOKEN (save your phone bookmark URL below)."
fi

ENV_FILE="${ROOT}/.env.cloud"
cat >"$ENV_FILE" <<EOF
# Generated by scripts/setup-cloud-mobile.sh — do not commit
GOLF_DATA_BUCKET=${GOLF_DATA_BUCKET}
GOLF_ACCESS_TOKEN=${GOLF_ACCESS_TOKEN}
GOLF_CLOUD_RUN_SERVICE=${SERVICE}
GOLF_CLOUD_RUN_REGION=${REGION}
EOF
chmod 600 "$ENV_FILE"
echo "Wrote ${ENV_FILE}"

export GOLF_DATA_BUCKET GOLF_ACCESS_TOKEN GOLF_CLOUD_RUN_SERVICE="$SERVICE" GOLF_CLOUD_RUN_REGION="$REGION"

SETTINGS="${GOLF_DASHBOARD_SETTINGS:-$ROOT/data/dashboard_settings.json}"
if [[ ! -f "$SETTINGS" ]]; then
  echo "Creating default dashboard settings at ${SETTINGS}..."
  GOLF_DASHBOARD_SETTINGS="$SETTINGS" uv run python -c \
    'from golf_analysis.api.settings_store import save_settings; save_settings({})'
fi

echo "Pushing data to GCS..."
"${ROOT}/scripts/push-dashboard-data.sh"

echo "Building and deploying Cloud Run (this may take several minutes)..."
"${ROOT}/scripts/deploy-cloud-run.sh"

URL="$(gcloud run services describe "$SERVICE" --region="$REGION" --format='value(status.url)')"
echo ""
echo "=== Phone bookmark ==="
echo "${URL}/?token=${GOLF_ACCESS_TOKEN}"
echo ""
echo "Day-to-day after new rounds:"
echo "  set -a && source .env.cloud && set +a"
echo "  ./scripts/push-dashboard-data.sh"
echo "  ./scripts/deploy-cloud-run.sh --reload-only"
